FROM node:20.11-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:20.11-alpine

WORKDIR /app

COPY --from=builder /app /app

CMD ["npm", "run", "start:dev:migrate"]
